/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'upcoming-shows': UpcomingShow;
    'music-releases': MusicRelease;
    'performance-history': PerformanceHistory;
    gallery: Gallery;
    'legacy-milestones': LegacyMilestone;
    testimonials: Testimonial;
    'experiences-services': ExperiencesService;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'upcoming-shows': UpcomingShowsSelect<false> | UpcomingShowsSelect<true>;
    'music-releases': MusicReleasesSelect<false> | MusicReleasesSelect<true>;
    'performance-history': PerformanceHistorySelect<false> | PerformanceHistorySelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    'legacy-milestones': LegacyMilestonesSelect<false> | LegacyMilestonesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'experiences-services': ExperiencesServicesSelect<false> | ExperiencesServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'home-page': HomePage;
    'contact-booking': ContactBooking;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'contact-booking': ContactBookingSelect<false> | ContactBookingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Media library for all website assets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage upcoming DJ Ganesh show listings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-shows".
 */
export interface UpcomingShow {
  id: number;
  title: string;
  date: string;
  time?: string | null;
  city: string;
  country: string;
  venue?: string | null;
  poster?: (number | null) | Media;
  ticketUrl?: string | null;
  showStatus: 'upcoming' | 'past' | 'cancelled';
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage DJ Ganesh music tracks and releases.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music-releases".
 */
export interface MusicRelease {
  id: number;
  title: string;
  genre: 'indo-tech' | 'afro-house' | 'afro-mashup' | 'bollyafro' | 'other';
  artist?: string | null;
  artwork?: (number | null) | Media;
  youtubeUrl?: string | null;
  /**
   * Optional: direct link to audio file.
   */
  audioUrl?: string | null;
  releaseDate?: string | null;
  description?: string | null;
  /**
   * Show this release in featured sections.
   */
  featured?: boolean | null;
  publishedStatus?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Track past DJ Ganesh performances worldwide.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-history".
 */
export interface PerformanceHistory {
  id: number;
  venue: string;
  city: string;
  country: string;
  year: number;
  description?: string | null;
  image?: (number | null) | Media;
  category?: ('india' | 'middle-east' | 'europe' | 'north-america' | 'southeast-asia' | 'other') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gallery albums with multiple images per album.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  album: string;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  publishedStatus?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Key milestones in DJ Ganesh career legacy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legacy-milestones".
 */
export interface LegacyMilestone {
  id: number;
  year: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  order?: number | null;
  publishedStatus?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Client and attendee testimonials for DJ Ganesh.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  testimonial: string;
  eventType?: string | null;
  location?: string | null;
  image?: (number | null) | Media;
  order?: number | null;
  publishedStatus?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * DJ Ganesh experience and service offerings (e.g. Royal Weddings, Club Residencies).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences-services".
 */
export interface ExperiencesService {
  id: number;
  title: string;
  shortDescription: string;
  detailedDescription?: string | null;
  image?: (number | null) | Media;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  ctaText?: string | null;
  ctaUrl?: string | null;
  order?: number | null;
  publishedStatus?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'upcoming-shows';
        value: number | UpcomingShow;
      } | null)
    | ({
        relationTo: 'music-releases';
        value: number | MusicRelease;
      } | null)
    | ({
        relationTo: 'performance-history';
        value: number | PerformanceHistory;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'legacy-milestones';
        value: number | LegacyMilestone;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'experiences-services';
        value: number | ExperiencesService;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-shows_select".
 */
export interface UpcomingShowsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  time?: T;
  city?: T;
  country?: T;
  venue?: T;
  poster?: T;
  ticketUrl?: T;
  showStatus?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music-releases_select".
 */
export interface MusicReleasesSelect<T extends boolean = true> {
  title?: T;
  genre?: T;
  artist?: T;
  artwork?: T;
  youtubeUrl?: T;
  audioUrl?: T;
  releaseDate?: T;
  description?: T;
  featured?: T;
  publishedStatus?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-history_select".
 */
export interface PerformanceHistorySelect<T extends boolean = true> {
  venue?: T;
  city?: T;
  country?: T;
  year?: T;
  description?: T;
  image?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  album?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  order?: T;
  publishedStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legacy-milestones_select".
 */
export interface LegacyMilestonesSelect<T extends boolean = true> {
  year?: T;
  title?: T;
  description?: T;
  image?: T;
  order?: T;
  publishedStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  testimonial?: T;
  eventType?: T;
  location?: T;
  image?: T;
  order?: T;
  publishedStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences-services_select".
 */
export interface ExperiencesServicesSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  detailedDescription?: T;
  image?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  ctaText?: T;
  ctaUrl?: T;
  order?: T;
  publishedStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site configuration, branding, SEO defaults, and contact information.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  seo?: {
    defaultSeoTitle?: string | null;
    defaultSeoDescription?: string | null;
  };
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'youtube' | 'twitter' | 'soundcloud' | 'spotify' | 'tiktok' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    contactEmail?: string | null;
    phone?: string | null;
  };
  bookingInfo?: string | null;
  footerContent?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage website navigation items and their order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        url: string;
        /**
         * Open in a new tab.
         */
        isExternal?: boolean | null;
        order?: number | null;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage content for the website homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    heroHeading?: string | null;
    heroSubheading?: string | null;
    heroImage?: (number | null) | Media;
    heroCtaText?: string | null;
    heroCtaUrl?: string | null;
  };
  artistIntro?: {
    introTitle?: string | null;
    introBio?: string | null;
    introImage?: (number | null) | Media;
  };
  statistics?: {
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  globalReach?: {
    heading?: string | null;
    /**
     * Manage city/location data from CMS instead of hardcoding in JS.
     */
    locations?:
      | {
          city: string;
          country: string;
          lat?: number | null;
          lng?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  featuredShows?: {
    heading?: string | null;
    shows?: (number | UpcomingShow)[] | null;
  };
  featuredMusic?: {
    heading?: string | null;
    tracks?: (number | MusicRelease)[] | null;
  };
  bookingCta?: {
    heading?: string | null;
    subheading?: string | null;
    ctaText?: string | null;
    ctaUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage contact and booking information for DJ Ganesh.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-booking".
 */
export interface ContactBooking {
  id: number;
  bookingEmail: string;
  enquiryEmail?: string | null;
  phone?: string | null;
  agency?: {
    agencyName?: string | null;
    agencyEmail?: string | null;
    agencyPhone?: string | null;
    agencyWebsite?: string | null;
  };
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'youtube' | 'twitter' | 'whatsapp' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  bookingCtaText?: string | null;
  bookingCtaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  favicon?: T;
  seo?:
    | T
    | {
        defaultSeoTitle?: T;
        defaultSeoDescription?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        contactEmail?: T;
        phone?: T;
      };
  bookingInfo?: T;
  footerContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        url?: T;
        isExternal?: T;
        order?: T;
        visible?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heroHeading?: T;
        heroSubheading?: T;
        heroImage?: T;
        heroCtaText?: T;
        heroCtaUrl?: T;
      };
  artistIntro?:
    | T
    | {
        introTitle?: T;
        introBio?: T;
        introImage?: T;
      };
  statistics?:
    | T
    | {
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  globalReach?:
    | T
    | {
        heading?: T;
        locations?:
          | T
          | {
              city?: T;
              country?: T;
              lat?: T;
              lng?: T;
              id?: T;
            };
      };
  featuredShows?:
    | T
    | {
        heading?: T;
        shows?: T;
      };
  featuredMusic?:
    | T
    | {
        heading?: T;
        tracks?: T;
      };
  bookingCta?:
    | T
    | {
        heading?: T;
        subheading?: T;
        ctaText?: T;
        ctaUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-booking_select".
 */
export interface ContactBookingSelect<T extends boolean = true> {
  bookingEmail?: T;
  enquiryEmail?: T;
  phone?: T;
  agency?:
    | T
    | {
        agencyName?: T;
        agencyEmail?: T;
        agencyPhone?: T;
        agencyWebsite?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  bookingCtaText?: T;
  bookingCtaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}