/**
 * Land/water mask of the world, 360 × 180 cells (1° per cell), one bit per
 * cell, row-major from lat +90 down to −90 and lng −180 to +180, packed
 * MSB-first and base64 encoded.
 *
 * Derived once at build time from the public-domain `earth-water` raster
 * (three-globe) and baked in so the tour map costs no network request and
 * needs no mapping library. Decode with `decodeWorldMask()`.
 */

export const WORLD_MASK_WIDTH = 360;
export const WORLD_MASK_HEIGHT = 180;

const WORLD_MASK_BASE64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//4ACX///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////B" +
  "//////7+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfjf/5////////wAAAAAAAAAAAMAAAAAHgAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAf//4Af//////8AAAAB7nwAAAAAAAAAAD8AAAAAAAAAAAAAAAAAAAAAAAAADzH3/4////////4AAAAAf0AAAAAA" +
  "AAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAIAAAP/Af///////8AAAAAHAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAADpCAM2PGAH/" +
  "//////4AAAAAAAAAAAAAB4AAAAB/8AAAAAAAAAAAAAAAAAAAAAH/wcz78AAAP/////8AAAAAAAAAAAADwAAAA///+AAAB/AAAAAA" +
  "AAAAAAAAAGAQAAAAAAAAH/////8AAAAAAAAAAAAOAAAAH///wAAAAAAAAAAAAAAAAAAAAP8AIe+c7gAAD/////wAAAAAAAAAAAA4" +
  "AAAH////v8DAAAAAAAAAAAAAAAAAAfP+4+Q74wAAB/////gAAAAAAAAAAADwAHgH///////4APgAAAAAwAAAAAAAAOP/4Ew//9AA" +
  "Bf////wAAAAAAAAAAADwAPL////////4kP/AAAAAAAAP8AAAAAH/+A8P//4AAv///+wAAAAAAB/AAAAAAfv/////////////8AAA" +
  "AAB///+A/WD//COBwP8AAn////AAAAAAA//4AAAA8Pv/////////////+9n8wAP///////+AYDPzwD8AAX///wAAAAAAH///wEDf" +
  "/3m/////////////////+AD////////+///3wY/wA///4AAAAAAAH///+I////v//////////////////4E//////8f////9gDv8" +
  "Af//gAAAAAAAf//88P////f/////////////////Dwf//////4/////6AD+YAf/wAAf8AAAA/8f+D///////////////////////" +
  "AgAf///////////zwz/gAP/gAAP4AAAB/4/+P//////////////////////8AAA///////////+CAA/gAH/gAAAAAAAP/j//////" +
  "///////////////////+AAH///////////4AgAGAAD/AAAAAAAA//H/////////////////////////6AAP///////8f//wAA/AA" +
  "AB/AAAAAAAB/+D/O////////////////////jP+AAAH/9z////////gAA/wAAAOAAAAAAAB//D7n///////////////////+A/YA" +
  "AAA/xAB///////gAA/wwAAAAAAAAAAA//gb///////////////////+cBgAAAAABwAAf//////4AA/94AAAAAAAAAQA5+A7/3///" +
  "/////////////4AAHAAAAAADIAAP//////4AAf/8AAAAAAAAA8AA+C///////////////////wAAfgAAAAAMAAAD///////wAP/+" +
  "AAAAAAAAA4AOcH///////////////////AAA/gAAAAAAAAAB///////8Af//AAAAAAAAAcANAH//////////////////8AAA/AAA" +
  "AAAAAAAAP///////x///wAAAAAAAHGAEDv//////////////v///+AAA8AAAAAAAAAABP////7//x///8AAAAAAAPHAf////////" +
  "////////f////6AA8AAAAAAAAAAAH////9//x///8AAAAAAAPPx//////////////////////6AAwAAAAAAAAAAAD///////9///" +
  "8AAAAAAAAPj//////////////////////6AAQAAAAAAAAAAAD///////////EAAAAAAAAAP//////////////////////zAAAAAA" +
  "AAAAAAAAA/////////+APAAAAAAAAA///////////////////////zAAAAAAAAAAAAAAAf/////j///gfAAAAAAAAP//////////" +
  "/////////////yAAAAAAAAAAAAAAAP////+B///gCgAAAAAAAH///////////////////////iAAAAAAAAAAAAAAAP/////////x" +
  "AAAAAAAAAD/////uP/x///3//////////AAAAAAAAAAAAAAAAP/////5D//+AAAAAAAAAB//v//GP/D+////////////+AAAAAAA" +
  "AAAAAAAAAP/////zn/8wAAAAAAAAAB//H/+AP+H+////////////8CAAAAAAAAAAAAAAAP/////zuPwAAAAAAAAADj/jj/8AD/H/" +
  "////////////4HgAAAAAAAAAAAAAAP/////zx/gAAAAAAAAAH/4Bw/8AB/B///+////////+AKAAAAAAAAAAAAAAAP//////v/gA" +
  "AAAAAAAAH/wAcP8PB/g////////////8AAAAAAAAAAAAAAAAAP///////8AAAAAAAAAAH/gMGPN///x///////////v4AMAAAAAA" +
  "AAAAAAAAAP///////8AAAAAAAAAAH/AICOP///h//////////+JwAMAAAAAAAAAAAAAAAH///////4AAAAAAAAAAH/AAAHH///g/" +
  "/////////8BwAIAAAAAAAAAAAAAAAD///////wAAAAAAAAAAH+AAYCH///w//////////+wYA4AAAAAAAAAAAAAAAD///////wAA" +
  "AAAAAAAAAgf+AABM//////////////gYD4AAAAAAAAAAAAAAAB///////wAAAAAAAAAAAh/+AAAA//////////////AYPwAAAAAA" +
  "AAAAAAAAAA///////gAAAAAAAAAAA//8AAAA//////////////AA+AAAAAAAAAAAAAAAAAP/////+AAAAAAAAAAAD//+AAAB////" +
  "//////////gCwAAAAAAAAAAAAAAAAAH/////8AAAAAAAAAAAH///4GAB//////////////gDAAAAAAAAAAAAAAAAAAC/////4AAA" +
  "AAAAAAAAP///8P4D//////////////wAAAAAAAAAAAAAAAAAAACf////4AAAAAAAAAAAP////v////////////////gAAAAAAAAA" +
  "AAAAAAAAAABP//hAYAAAAAAAAAAAP/////////H///////////wAAAAAAAAAAAAAAAAAAAAv/+AAYAAAAAAAAAAAf/////////H/" +
  "//////////gAAAAAAAAAAAAAAAAAAAAz/+AAcAAAAAAAAAAB///////8//h///////////gAAAAAAAAAAAAAAAAAAAAR/+AAMAAA" +
  "AAAAAAAD///////8//wH//////////AAAAAAAAAAAAAAAAAAAAAJ/+AAEAAAAAAAAAAH///////+f/8B/////////+AAAAAAAAAA" +
  "AAAAAAAAAAAI/8AAAAAAAAAAAAAH///////+P/4YAf///////8QAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAP///////+H//+" +
  "AP///////4gAAAAAAAAAAAAAAAAAAAAAP8AAuAAAAAAAAAAP////////H///AD///v///AAAAAAAAAAAAAAAAAAAAAAAH+AYBgAA" +
  "AAAAAAAf////////n//+ADf/4P//YAAAAAAAAAAAAAAAAAAAAAAAH+B4AYAAAAAAAAAP////////j//8AAf/4H/8AAAAAAAAAAAA" +
  "AAAAgAAAAAAAH/BwABwAAAAAAAAP////////h//8AAf/gD/8YAAAAAAAAAAAAAAAAAAAAAAAB/nwAAxAAAAAAAAP////////x//4" +
  "AAf/AD/8QAQAAAAAAAAAAAAAAAAAAAAAAf/wAAAAAAAAAAAP////////4//gAAf+AB/+AAwAAAAAAAAAAAAAAAAAAAAAAH/wAAAA" +
  "AAAAAAAP////////4f+AAAf8ADf/AAwAAAAAAAAAAAAAAAAAAAAAAAH/AAAAAAAAAAAf////////8f8AAAPwAAP/gAgAAAAAAAAA" +
  "AAAAAAAAAAAAAAD/gAAAAAAAAAAf////////+fgAAAPwAAP/gAQAAAAAAAAAAAAAAAAAAAAAAAAfAAAAAAAAAAAf/////////eAA" +
  "AAHwAAP/gAEAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAf/////////gAAAAHwAAE/gAAAAAAAAAAAAAAAAAAAAAAAAAABABIA" +
  "AAAAAAAH/////////gIAAADwAAEfgAIAAAAAAAAAAAAAAAAAAAAAAAADgH/IAAAAAAAD/////////34AAADwAAIOAAEAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAgPf+AAAAAAAB//////////4AAADgAAIEAAAAAAAAAAAAAAAAAAAAAAAAAAAAc///AAAAAAAB//////////wA" +
  "AABIAAMAAADAAAAAAAAAAAAAAAAAAAAAAAAAE///gAAAAAAA//////////wAAAAMAAEAAADgAAAAAAAAAAAAAAAAAAAAAAAAAf//" +
  "wAAAAAAAf/////////gAAAAMAADAAMCAAAAAAAAAAAAAAAAAAAAAAAAAAf///gAAAAAAP/B///////gAAAAAAADgAOAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAf///wAAAAAAAAAn//////AAAAAAAAxgA8AAAAAAAAAAAAAAAAAAAAAAAAAAAf///4AAAAAAAAAD/////+AA" +
  "AAAAAAZgB8AAAAAAAAAAAAAAAAAAAAAAAAAAA////4AAAAAAAAAD/////8AAAAAAAAMwH8AAAAAAAAAAAAAAAAAAAAAAAAAAB///" +
  "/8AAAAAAAAAD/////wAAAAAAAAHQf8AAAAAAAAAAAAAAAAAAAAAAAAAAD////8AAAAAAAAAD/////gAAAAAAAAHgf8EAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAD////+AAAAAAAAAH///z/AAAAAAAAADgf4AAgAAAAAAAAAAAAAAAAAAAAAAAH/////4AAAAAAAAH///z/AAA" +
  "AAAAAABwP5wAwAAAAAAAAAAAAAAAAAAAAAAAD/////+AAAAAAAAD////+AAAAAAAAAB8PxwAT4AAAAAAAAAAAAAAAAAAAAAAD///" +
  "///4AAAAAAAB////8AAAAAAAAAA8AxQAf+AAAAAAAAAAAAAAAAAAAAAAH//////8AAAAAAAA//+/4AAAAAAAAAAcAAIAD/gAAAAA" +
  "AAAAAAAAAAAAAAAAH///////gAAAAAAA//+/4AAAAAAAAAAMAAAAA/xwAAAAAAAAAAAAAAAAAAAAD///////gAAAAAAAf///4AAA" +
  "AAAAAAADgAAAAf8AAAAAAAAAAAAAAAAAAAAAB///////gAAAAAAAf///4AAAAAAAAAAB+AAAA/4AAAAAAAAAAAAAAAAAAAAAB///" +
  "////gAAAAAAAf///4AAAAAAAAAAAAMhAAOMAAAAAAAAAAAAAAAAAAAAAA///////AAAAAAAAf///8AAAAAAAAAAAAACAAAGAAAAA" +
  "AAAAAAAAAAAAAAAAA//////+AAAAAAAAP///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////+AAAAAAAAP//98AAA" +
  "AAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAf/////8AAAAAAAAf//9+AQAAAAAAAAAAAAB+CAAAAAAAAAAAAAAAAAAAAAAAP//" +
  "///4AAAAAAAAf///+AwAAAAAAAAAAAAD8DAAAAAAAAAAAAAAAAAAAAAAAP/////4AAAAAAAA////+AwAAAAAAAAAAAAz8DgAAAAA" +
  "AAAAAAAAAAAAAAAAAH3////4AAAAAAAA////8BwAAAAAAAAAAAB/8HgAAAAAAAAAAAAAAAAAAAAAAB/////4AAAAAAAA////8PwA" +
  "AAAAAAAAAAD//HwAAAAAAAAAAAAAAAAAAAAAAAf////4AAAAAAAA////wPgAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAP/" +
  "///wAAAAAAAA////gPgAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAP////wAAAAAAAAf//+APgAAAAAAAAAAAf///4AAAAA" +
  "AAAAAAAAAAAAAAAAAAP////wAAAAAAAAf//+APgAAAAAAAAAAD////+AAAAAAAAAAAAAAAAAAAAAAAP////gAAAAAAAAP//+APAA" +
  "AAAAAAAAAf////+AAAAAAAAAAAAAAAAAAAAAAAP////AAAAAAAAAP//+AfAAAAAAAAAAA//////AAAAAAAAAAAAAAAAAAAAAAAP/" +
  "//4AAAAAAAAAP//+APAAAAAAAAAAA//////gAAAAAAAAAAAAAAAAAAAAAAP///gAAAAAAAAAH//+AOAAAAAAAAAAB//////wAAAA" +
  "AAAAAAAAAAAAAAAAAAf///AAAAAAAAAAH//4AAAAAAAAAAAAA//////4AAAAAAAAAAAAAAAAAAAAAAf//+AAAAAAAAAAH//4AAAA" +
  "AAAAAAAAA//////4AAAAAAAAAAAAAAAAAAAAAAf//+AAAAAAAAAAH//4AAAAAAAAAAAAA//////4AAAAAAAAAAAAAAAAAAAAAAf/" +
  "/+AAAAAAAAAAD//wAAAAAAAAAAAAA//////8AAAAAAAAAAAAAAAAAAAAAAf//8AAAAAAAAAAB//gAAAAAAAAAAAAAf/////4AAAA" +
  "AAAAAAAAAAAAAAAAAA///4AAAAAAAAAAB//gAAAAAAAAAAAAAf/////4AAAAAAAAAAAAAAAAAAAAAA///wAAAAAAAAAAA//AAAAA" +
  "AAAAAAAAAP/////4AAAAAAAAAAAAAAAAAAAAAAf//gAAAAAAAAAAA/+AAAAAAAAAAAAAAP+AP//wAAAAAAAAAAAAAAAAAAAAAA//" +
  "/gAAAAAAAAAAA/4AAAAAAAAAAAAAAf8AG//gAAAAAAAAAAAAAAAAAAAAAA//3AAAAAAAAAAAAQAAAAAAAAAAAAAAAOAAA//gAAAA" +
  "AAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAABAAAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAP/AAAAAAAAAAAAAAAAAAAAAAD//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/AAAAQAAAAAAAAAAAAAAAAAB//" +
  "wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAAAcAAAAAAAAAAAAAAAAAB/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4" +
  "AAAAAAAAAAAAAAAAAD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAD/gAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAcAAADAAAAAAAAAAAAAAAAAAB/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAHAAAAAAAAAAAAAAAAAAB/g" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4A" +
  "AAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAH+AAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+A" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AQAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAABwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAAH4" +
  "AAAD+B/+HgHD/AAAAAAAAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAD//kAAD//////////AAAAAAAAAAAAAAAAAAAAAAAAB+" +
  "AAAAAAAAAAAAAAAAB////8w////////////2AAAAAAAAAAAAAAAAAAAAAB/+AAAAAAAAABgAMAA+D///////////////////8AAA" +
  "AAAAAAAAAAAAAAAAAD/+AAAAAAAAF///////////////////////////+gAAAAAAAAAAAAAAAAAAAH//AAAAAAAA////////////" +
  "//////////////////wAAAAAAAAAAAAAB/gAAB//AAAAAAAP//////////////////////////////wAAAAAAAAABgAAB//+H///" +
  "AAAAAAD//////////////////////////////8AAAAAAAAAD///4A//////+AAAAAA///////////////////////////////4AA" +
  "AAAAABX/////////////gAAAAD///////////////////////////////gAAAAAAA///////////////+AAAA///////////////" +
  "/////////////////gAAAAAD//////////////////AAf////////////////////////////////x+A//7/////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" ;

/** Unpacks the mask into one byte per cell (1 = land) for O(1) lookups. */
export function decodeWorldMask(): Uint8Array {
  const binary = atob(WORLD_MASK_BASE64);
  const cells = new Uint8Array(WORLD_MASK_WIDTH * WORLD_MASK_HEIGHT);

  for (let i = 0; i < cells.length; i++) {
    const byte = binary.charCodeAt(i >> 3);
    cells[i] = (byte >> (7 - (i & 7))) & 1;
  }

  return cells;
}

/** True when the given coordinate falls on land. */
export function isLand(cells: Uint8Array, lat: number, lng: number): boolean {
  const x = Math.min(
    WORLD_MASK_WIDTH - 1,
    Math.max(0, Math.floor(((lng + 180) / 360) * WORLD_MASK_WIDTH)),
  );
  const y = Math.min(
    WORLD_MASK_HEIGHT - 1,
    Math.max(0, Math.floor(((90 - lat) / 180) * WORLD_MASK_HEIGHT)),
  );

  return cells[y * WORLD_MASK_WIDTH + x] === 1;
}
